### ISSUE TITLE
[Bug] Development on MS Windows

### ISSUE THREAD

**Issue by nodgear** [ptkdev-boilerplate/svelte-electron-boilerplate#1]
### Versions

-   **App Version:** any
-   **Node Version:** v14.15.3
-   **Operating System:** Windows 10x64
-   **Browser:** irrelevant

### Expected Behavior
Running tsnode  + debug and starting dev mode for TS.
Erasing files would be done within node, since windows would ned to run `del -f`/`del /f` instead

### Actual Behavior
script `run` uses rm as way to delete rollup and dist previous files.
But an error saying rm is not a command will be thrown (powershell uses rm as alias for del, but even running everything from Powershell 7 doesn't make this error go away)
### Steps to Reproduce

1. Be on windows (pref: Powerhsell)
2. Run yarn run dev or npm run dev
3. Notice issue

**Comment by ptkdev** [comment]
Hi!
On windows is recomended use [WLS2](https://docs.microsoft.com/en-us/windows/wsl/install-win10) for development with typescript/node.

In next release i try replace "rm" with "shelljs.rm()"

**Comment by ptkdev** [comment]
@nodgear fixed in nightly branch.
