### ISSUE TITLE
Allow nodeJS process variable

### ISSUE THREAD

**Issue by Wilbert-mad** [ptkdev-boilerplate/svelte-electron-boilerplate#2]
### Feature description

If there's a way to get node `process` please add.

### Feature motivation

I'm currently trying to use the process variable to get the user's user path; `process.env[process.platform === 'win32' ? 'USERPROFILE' : 'HOME']` but I keep getting a reference error. this should allow for better use cases like saving local data for a user in json or SQLite database.

**Comment by ptkdev** [comment]
See [process](https://www.electronjs.org/docs/api/process).
